version: '3.8'

services:
  lambda_ui_v2:
    build:
      context: ./lambda_ui_v2
    ports:
      - "8080:80"

  lambda_ai:
    build:
      context: ./lambda_ai
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./lambda_ai/.env

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase

volumes:
  postgres_data:
